# Generated by Django 3.0.8 on 2020-07-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=126)),
                ('last_name', models.CharField(max_length=126)),
                ('phone_number', models.BigIntegerField()),
                ('client_member_id', models.BigIntegerField()),
                ('account_id', models.BigIntegerField()),
            ],
        ),
    ]
