# Generated by Django 3.0.8 on 2020-07-05 01:42

from django.db import migrations, models
import mp_apps.mp_api.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=126)),
                ('last_name', models.CharField(max_length=126)),
                ('phone_number', models.BigIntegerField()),
                ('client_member_id', models.BigIntegerField()),
                ('account_id', models.BigIntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['account_id'], name='mp_api_memb_account_0ea437_idx'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('phone_number', 'account_id'), name='unique-phone_number-account_id'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('client_member_id', 'account_id'), name='unique-client_member_id-account_id'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=mp_apps.mp_api.utils.random_file_name)),
            ],
        ),
    ]
