# Generated by Django 3.0.8 on 2020-07-04 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['id']},
        ),
    ]
