# Generated by Django 3.0.8 on 2020-07-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_api', '0002_auto_20200704_0002'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['account_id'], name='mp_api_memb_account_0ea437_idx'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('phone_number', 'account_id'), name='unique-phone_number-account_id'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('client_member_id', 'account_id'), name='unique-client_member_id-account_id'),
        ),
    ]
