# Generated by Django 3.0.8 on 2020-07-04 21:34

from django.db import migrations, models
import mp_apps.mp_api.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mp_api', '0005_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=mp_apps.mp_api.utils.random_file_name),
        ),
    ]
